/** S1 IS · Chapter 1 — Introduction to Science (1.1–1.7) */
export const QUIZ_SECTIONS = [
  { id: "1.1", label: "1.1", labelZh: "1.1" },
  { id: "1.2", label: "1.2", labelZh: "1.2" },
  { id: "1.3", label: "1.3", labelZh: "1.3" },
  { id: "1.4", label: "1.4", labelZh: "1.4" },
  { id: "1.5", label: "1.5", labelZh: "1.5" },
  { id: "1.6", label: "1.6", labelZh: "1.6" },
  { id: "1.7", label: "1.7", labelZh: "1.7" },
];

export const QUIZ_ITEMS = [
  // —— 1.1 ——
  {
    id: "11-1",
    section: "1.1",
    difficulty: "Foundation",
    stem: "In the plant growth and light investigation, a student notices that plants near the window grow faster than those far from the window. Which stage of scientific investigation is this?",
    options: [
      { key: "A", text: "Observation" },
      { key: "B", text: "Hypothesis" },
      { key: "C", text: "Data processing and analysis" },
      { key: "D", text: "Drawing a conclusion" },
    ],
    answer: "A",
    hint: "This is noticing something in the real world before asking why.",
  },
  {
    id: "11-2",
    section: "1.1",
    difficulty: "Foundation",
    stem: "A student thinks, “Maybe more sunlight allows plants to grow faster.” Which stage of scientific investigation is this?",
    options: [
      { key: "A", text: "Observation" },
      { key: "B", text: "Asking a question" },
      { key: "C", text: "Hypothesis" },
      { key: "D", text: "Designing and performing an experiment" },
    ],
    answer: "C",
    hint: "A hypothesis is a possible explanation you can test.",
  },
  {
    id: "11-3",
    section: "1.1",
    difficulty: "Standard",
    stem: "A student places two identical plants — one near the window and one inside the room — gives both the same water and fertilizer, and records their heights each week. Which stage of scientific investigation is this?",
    options: [
      { key: "A", text: "Asking a question" },
      { key: "B", text: "Designing and performing an experiment" },
      { key: "C", text: "Data processing and analysis" },
      { key: "D", text: "Drawing a conclusion" },
    ],
    answer: "B",
    hint: "Planning the setup, controlling conditions, and collecting measurements is the experiment stage.",
  },
  {
    id: "11-4",
    section: "1.1",
    difficulty: "Foundation",
    stem: "The student organizes the weekly plant heights into a table and plots a growth curve. Which stage of scientific investigation is this?",
    options: [
      { key: "A", text: "Observation" },
      { key: "B", text: "Hypothesis" },
      { key: "C", text: "Designing and performing an experiment" },
      { key: "D", text: "Data processing and analysis" },
    ],
    answer: "D",
    hint: "Tables and graphs help you process and analyse collected data.",
  },
  {
    id: "11-5",
    section: "1.1",
    difficulty: "Foundation",
    stem: "The student finds that the plant near the window grows noticeably taller and makes a conclusion based on the data. Which stage of scientific investigation is this?",
    options: [
      { key: "A", text: "Drawing a conclusion" },
      { key: "B", text: "Asking a question" },
      { key: "C", text: "Hypothesis" },
      { key: "D", text: "Observation" },
    ],
    answer: "A",
    hint: "A conclusion uses the results to answer the investigation question.",
  },
  // —— 1.2 ——
  {
    id: "12-1",
    section: "1.2",
    difficulty: "Foundation",
    stem: "Research question: “Does the amount of screen time affect eye strain?” What is the independent variable?",
    options: [
      { key: "A", text: "Level of eye strain" },
      { key: "B", text: "Duration of screen time" },
      { key: "C", text: "Type of phone used" },
      { key: "D", text: "Age of the student" },
    ],
    answer: "B",
    hint: "The independent variable is the factor you change on purpose.",
  },
  {
    id: "12-2",
    section: "1.2",
    difficulty: "Foundation",
    stem: "Research question: “Does the amount of screen time affect eye strain?” What is the dependent variable?",
    options: [
      { key: "A", text: "Duration of screen time" },
      { key: "B", text: "Brightness of the screen" },
      { key: "C", text: "Level of eye strain" },
      { key: "D", text: "Time of day" },
    ],
    answer: "C",
    hint: "The dependent variable is what you measure to see the effect.",
  },
  {
    id: "12-3",
    section: "1.2",
    difficulty: "Standard",
    stem: "In the plant growth and light experiment, one plant is placed near the window and one inside the room. What is the independent variable?",
    options: [
      { key: "A", text: "Amount of light / plant location" },
      { key: "B", text: "Plant height" },
      { key: "C", text: "Amount of water" },
      { key: "D", text: "Amount of fertilizer" },
    ],
    answer: "A",
    hint: "Location changes how much light each plant receives — that is what is deliberately varied.",
  },
  {
    id: "12-4",
    section: "1.2",
    difficulty: "Foundation",
    stem: "In the same plant experiment, the student records plant heights each week. What is the dependent variable?",
    options: [
      { key: "A", text: "Amount of fertilizer" },
      { key: "B", text: "Type of pot" },
      { key: "C", text: "Amount of light / plant location" },
      { key: "D", text: "Plant height" },
    ],
    answer: "D",
    hint: "Height is the measured outcome that may change because of light.",
  },
  {
    id: "12-5",
    section: "1.2",
    difficulty: "Standard",
    stem: "In the plant growth and light experiment, which of the following is a controlled variable?",
    options: [
      { key: "A", text: "Amount of light / plant location" },
      { key: "B", text: "Amount of water given to each plant" },
      { key: "C", text: "Plant height after one week" },
      { key: "D", text: "How fast the plant grows" },
    ],
    answer: "B",
    hint: "Controlled variables are kept the same so the test is fair (e.g. same water and fertilizer).",
  },
  // —— 1.3 ——
  {
    id: "13-1",
    section: "1.3",
    difficulty: "Foundation",
    stem: "Which hazard warning symbol applies to ethanol used in the laboratory?",
    options: [
      { key: "A", text: "Flammable" },
      { key: "B", text: "Explosive" },
      { key: "C", text: "Corrosive" },
      { key: "D", text: "Irritant" },
    ],
    answer: "A",
    hint: "Ethanol is kept away from heat and flame.",
  },
  {
    id: "13-2",
    section: "1.3",
    difficulty: "Foundation",
    stem: "Which precaution is most appropriate when handling a corrosive chemical such as hydrochloric acid?",
    options: [
      { key: "A", text: "Keep away from heat and flame only" },
      { key: "B", text: "Avoid shock that may cause an explosion" },
      { key: "C", text: "Wear safety goggles and protective gloves" },
      { key: "D", text: "Open all windows and turn off the gas supply" },
    ],
    answer: "C",
    hint: "Corrosive substances can damage skin and eyes.",
  },
  {
    id: "13-3",
    section: "1.3",
    difficulty: "Foundation",
    stem: "Which hazard warning symbol would you expect on dynamite?",
    options: [
      { key: "A", text: "Flammable" },
      { key: "B", text: "Explosive" },
      { key: "C", text: "Toxic" },
      { key: "D", text: "Corrosive" },
    ],
    answer: "B",
    hint: "Explosives must be kept away from heat, flame, and shock.",
  },
  {
    id: "13-4",
    section: "1.3",
    difficulty: "Standard",
    stem: "What is the main function of a fire blanket?",
    options: [
      { key: "A", text: "Flush chemicals from the eyes" },
      { key: "B", text: "Protect clothing from spills" },
      { key: "C", text: "Provide ventilation for toxic fumes" },
      { key: "D", text: "Smother a small fire by cutting off the oxygen supply" },
    ],
    answer: "D",
    hint: "Removing oxygen is one way to break the fire triangle.",
  },
  {
    id: "13-5",
    section: "1.3",
    difficulty: "Standard",
    stem: "If chemicals get into the eyes, what should you do first?",
    options: [
      { key: "A", text: "Wash the eyes with distilled water from an eye wash bottle" },
      { key: "B", text: "Rub the eyes firmly to remove the chemical" },
      { key: "C", text: "Place the eyes under a sand bucket" },
      { key: "D", text: "Turn off the gas supply and open the windows" },
    ],
    answer: "A",
    hint: "Use the eye wash bottle to flush and cleanse the eyes.",
  },
  // —— 1.4 ——
  {
    id: "14-1",
    section: "1.4",
    difficulty: "Foundation",
    stem: "Which of the following apparatus can be used for holding about 2 cm³ of water?",
    options: [
      { key: "A", text: "Test tube" },
      { key: "B", text: "Beaker" },
      { key: "C", text: "Filter funnel" },
      { key: "D", text: "Gas jar" },
    ],
    answer: "A",
    hint: "A test tube holds a smaller amount of liquid or solid.",
  },
  {
    id: "14-2",
    section: "1.4",
    difficulty: "Foundation",
    stem: "Which of the following apparatus can be used for measuring 15 cm³ of water?",
    options: [
      { key: "A", text: "Reagent bottle" },
      { key: "B", text: "Beaker" },
      { key: "C", text: "Measuring cylinder" },
      { key: "D", text: "Watch glass" },
    ],
    answer: "C",
    hint: "A measuring cylinder has marks for measuring liquid volume.",
  },
  {
    id: "14-3",
    section: "1.4",
    difficulty: "Foundation",
    stem: "Which of the following apparatus can be used for stirring liquids?",
    options: [
      { key: "A", text: "Spatula" },
      { key: "B", text: "Glass rod" },
      { key: "C", text: "Dropper" },
      { key: "D", text: "Tongs" },
    ],
    answer: "B",
    hint: "A glass rod is used to stir liquids.",
  },
  {
    id: "14-4",
    section: "1.4",
    difficulty: "Foundation",
    stem: "Which of the following apparatus can be used for transferring a small amount of liquid?",
    options: [
      { key: "A", text: "Test tube" },
      { key: "B", text: "Dropper" },
      { key: "C", text: "Watch glass" },
      { key: "D", text: "Spatula" },
    ],
    answer: "B",
    hint: "A dropper transfers a small amount of liquid.",
  },
  {
    id: "14-5",
    section: "1.4",
    difficulty: "Standard",
    stem: "When drawing a vertical section (cross-sectional) diagram of a container, which rule is correct?",
    options: [
      { key: "A", text: "Draw the container in 3D with shading" },
      { key: "B", text: "Use double lines for every wall to show thickness" },
      { key: "C", text: "Shade the liquid heavily so it looks solid" },
      { key: "D", text: "Use one clean line for each wall (not double-walled or 3D)" },
    ],
    answer: "D",
    hint: "Notes say: use only one line, and do not draw 3D or shade.",
  },
  // —— 1.5 ——
  {
    id: "15-1",
    section: "1.5",
    difficulty: "Foundation",
    stem: "What is the numerical meaning of the prefix kilo- (k)?",
    options: [
      { key: "A", text: "0.001" },
      { key: "B", text: "1000" },
      { key: "C", text: "0.01" },
      { key: "D", text: "100" },
    ],
    answer: "B",
    hint: "kilo- means thousand (e.g. 1 km = 1000 m).",
  },
  {
    id: "15-2",
    section: "1.5",
    difficulty: "Foundation",
    stem: "When measuring liquid volume with a measuring cylinder, where should you read the scale?",
    options: [
      { key: "A", text: "At the top of the meniscus" },
      { key: "B", text: "At the average of the top and bottom of the meniscus" },
      { key: "C", text: "At the level of the bottom of the meniscus" },
      { key: "D", text: "From the side at an angle below the liquid surface" },
    ],
    answer: "C",
    hint: "Read at the bottom of the meniscus, looking from vertically above where appropriate.",
  },
  {
    id: "15-3",
    section: "1.5",
    difficulty: "Foundation",
    stem: "Which statement about volume units is correct?",
    options: [
      { key: "A", text: "1 mL = 1 cm³" },
      { key: "B", text: "1 mL = 1000 cm³" },
      { key: "C", text: "1 L = 1 cm³" },
      { key: "D", text: "1 m³ = 1000 cm³" },
    ],
    answer: "A",
    hint: "Millilitre and cubic centimetre are equal in volume.",
  },
  {
    id: "15-4",
    section: "1.5",
    difficulty: "Standard",
    stem: "When finding the volume of foam cubes by displacement in a measuring cylinder, why is a metal block needed?",
    options: [
      { key: "A", text: "The metal block measures temperature" },
      { key: "B", text: "Foam would float on water" },
      { key: "C", text: "Foam dissolves in water" },
      { key: "D", text: "The metal block removes the meniscus" },
    ],
    answer: "B",
    hint: "Foam floats, so a denser object is used to help submerge it for displacement.",
  },
  {
    id: "15-5",
    section: "1.5",
    difficulty: "Standard",
    stem: "Convert 6 L to millilitres (mL).",
    options: [
      { key: "A", text: "6 mL" },
      { key: "B", text: "60 mL" },
      { key: "C", text: "600 mL" },
      { key: "D", text: "6000 mL" },
    ],
    answer: "D",
    hint: "1 L = 1000 mL, so 6 × 1000 = 6000 mL.",
  },
  // —— 1.6 ——
  {
    id: "16-1",
    section: "1.6",
    difficulty: "Foundation",
    stem: "What is the first step when using a Bunsen burner?",
    options: [
      { key: "A", text: "Turn on the gas tap" },
      { key: "B", text: "Place the Bunsen burner on a heat-proof mat" },
      { key: "C", text: "Open the air hole fully" },
      { key: "D", text: "Light the flame" },
    ],
    answer: "B",
    hint: "Protect the bench from heat before lighting.",
  },
  {
    id: "16-2",
    section: "1.6",
    difficulty: "Standard",
    stem: "What happens if you open the air hole fully?",
    options: [
      { key: "A", text: "The flame becomes yellow and quiet" },
      { key: "B", text: "The flame becomes blue and noisy" },
      { key: "C", text: "The flame burns inside the chimney, causing strike back" },
      { key: "D", text: "The flame extinguishes immediately" },
    ],
    answer: "C",
    hint: "Opening the air hole fully can cause strike back.",
  },
  {
    id: "16-3",
    section: "1.6",
    difficulty: "Foundation",
    stem: "What is the purpose of closing the air hole before lighting the Bunsen burner?",
    options: [
      { key: "A", text: "To make the flame blue" },
      { key: "B", text: "To ensure a luminous flame for easier ignition" },
      { key: "C", text: "To increase the temperature of the flame" },
      { key: "D", text: "To reduce noise levels" },
    ],
    answer: "B",
    hint: "A bright yellow luminous flame is stable and easier to see when lighting.",
  },
  {
    id: "16-4",
    section: "1.6",
    difficulty: "Foundation",
    stem: "Which of the following conditions indicates a non-luminous flame?",
    options: [
      { key: "A", text: "Yellow colour, irregular shape, quiet" },
      { key: "B", text: "Blue colour, regular shape, noisy" },
      { key: "C", text: "Green colour, hissing sound" },
      { key: "D", text: "Yellow colour, regular shape, quiet" },
    ],
    answer: "B",
    hint: "Non-luminous flames are hotter and used for heating.",
  },
  {
    id: "16-5",
    section: "1.6",
    difficulty: "Standard",
    stem: "What should you do if you observe a green flame and hear hissing sounds?",
    options: [
      { key: "A", text: "Adjust the collar to close the air hole" },
      { key: "B", text: "Turn off the gas tap immediately" },
      { key: "C", text: "Touch the chimney to fix the problem" },
      { key: "D", text: "Fully open the air hole" },
    ],
    answer: "B",
    hint: "That is strike back — do not touch the chimney or collar.",
  },
  // —— 1.7 ——
  {
    id: "17-1",
    section: "1.7",
    difficulty: "Foundation",
    stem: "Gravity is an example of a …",
    options: [
      { key: "A", text: "Invention" },
      { key: "B", text: "Discovery" },
      { key: "C", text: "Model" },
      { key: "D", text: "Classification" },
    ],
    answer: "B",
    hint: "Gravity already existed in nature; it was uncovered, not created.",
  },
  {
    id: "17-2",
    section: "1.7",
    difficulty: "Foundation",
    stem: "An airplane is an example of a …",
    options: [
      { key: "A", text: "Invention" },
      { key: "B", text: "Discovery" },
      { key: "C", text: "Pattern" },
      { key: "D", text: "Branch of geology" },
    ],
    answer: "A",
    hint: "An invention is a new device or method that did not previously exist.",
  },
  {
    id: "17-3",
    section: "1.7",
    difficulty: "Foundation",
    stem: "Experimenting with acids and alkalis to understand pH levels belongs mainly to which branch of science?",
    options: [
      { key: "A", text: "Physics" },
      { key: "B", text: "Biology" },
      { key: "C", text: "Chemistry" },
      { key: "D", text: "Astronomy" },
    ],
    answer: "C",
    hint: "Chemistry studies reactions of matter.",
  },
  {
    id: "17-4",
    section: "1.7",
    difficulty: "Foundation",
    stem: "Investigating the formation and evolution of stars and galaxies belongs mainly to which branch of science?",
    options: [
      { key: "A", text: "Geology" },
      { key: "B", text: "Medicine" },
      { key: "C", text: "Chemistry" },
      { key: "D", text: "Astronomy" },
    ],
    answer: "D",
    hint: "Astronomy is the study of stars and the Universe.",
  },
  {
    id: "17-5",
    section: "1.7",
    difficulty: "Standard",
    stem: "Comparing similarities and differences between objects and sorting those with similarities into groups is called …",
    options: [
      { key: "A", text: "Classifying" },
      { key: "B", text: "Pattern seeking" },
      { key: "C", text: "Model building" },
      { key: "D", text: "Discovery" },
    ],
    answer: "A",
    hint: "Pattern seeking looks for regularities; model building represents things too big or small to see.",
  },
];
