/** S1 IS · Chapter 1 — Introduction to Science (1.1 + 1.2) */
export const QUIZ_SECTIONS = [
  { id: "1.1", label: "1.1", labelZh: "1.1" },
  { id: "1.2", label: "1.2", labelZh: "1.2" },
];

export const QUIZ_ITEMS = [
  {
    id: "11-1",
    section: "1.1",
    difficulty: "Foundation",
    stem: "In the plant growth and light investigation, a student notices that plants near the window grow faster than those far from the window. Which stage of scientific investigation is this?",
    options: [
      { key: "A", text: "Observation" },
      { key: "B", text: "Hypothesis" },
      { key: "C", text: "Data processing and analysis" },
      { key: "D", text: "Drawing a conclusion" },
    ],
    answer: "A",
    hint: "This is noticing something in the real world before asking why.",
  },
  {
    id: "11-2",
    section: "1.1",
    difficulty: "Foundation",
    stem: "A student thinks, “Maybe more sunlight allows plants to grow faster.” Which stage of scientific investigation is this?",
    options: [
      { key: "A", text: "Observation" },
      { key: "B", text: "Asking a question" },
      { key: "C", text: "Hypothesis" },
      { key: "D", text: "Designing and performing an experiment" },
    ],
    answer: "C",
    hint: "A hypothesis is a possible explanation you can test.",
  },
  {
    id: "11-3",
    section: "1.1",
    difficulty: "Standard",
    stem: "A student places two identical plants — one near the window and one inside the room — gives both the same water and fertilizer, and records their heights each week. Which stage of scientific investigation is this?",
    options: [
      { key: "A", text: "Asking a question" },
      { key: "B", text: "Designing and performing an experiment" },
      { key: "C", text: "Data processing and analysis" },
      { key: "D", text: "Drawing a conclusion" },
    ],
    answer: "B",
    hint: "Planning the setup, controlling conditions, and collecting measurements is the experiment stage.",
  },
  {
    id: "11-4",
    section: "1.1",
    difficulty: "Foundation",
    stem: "The student organizes the weekly plant heights into a table and plots a growth curve. Which stage of scientific investigation is this?",
    options: [
      { key: "A", text: "Observation" },
      { key: "B", text: "Hypothesis" },
      { key: "C", text: "Designing and performing an experiment" },
      { key: "D", text: "Data processing and analysis" },
    ],
    answer: "D",
    hint: "Tables and graphs help you process and analyse collected data.",
  },
  {
    id: "11-5",
    section: "1.1",
    difficulty: "Foundation",
    stem: "The student finds that the plant near the window grows noticeably taller and makes a conclusion based on the data. Which stage of scientific investigation is this?",
    options: [
      { key: "A", text: "Drawing a conclusion" },
      { key: "B", text: "Asking a question" },
      { key: "C", text: "Hypothesis" },
      { key: "D", text: "Observation" },
    ],
    answer: "A",
    hint: "A conclusion uses the results to answer the investigation question.",
  },
  {
    id: "12-1",
    section: "1.2",
    difficulty: "Foundation",
    stem: "Research question: “Does the amount of screen time affect eye strain?” What is the independent variable?",
    options: [
      { key: "A", text: "Level of eye strain" },
      { key: "B", text: "Duration of screen time" },
      { key: "C", text: "Type of phone used" },
      { key: "D", text: "Age of the student" },
    ],
    answer: "B",
    hint: "The independent variable is the factor you change on purpose.",
  },
  {
    id: "12-2",
    section: "1.2",
    difficulty: "Foundation",
    stem: "Research question: “Does the amount of screen time affect eye strain?” What is the dependent variable?",
    options: [
      { key: "A", text: "Duration of screen time" },
      { key: "B", text: "Brightness of the screen" },
      { key: "C", text: "Level of eye strain" },
      { key: "D", text: "Time of day" },
    ],
    answer: "C",
    hint: "The dependent variable is what you measure to see the effect.",
  },
  {
    id: "12-3",
    section: "1.2",
    difficulty: "Standard",
    stem: "In the plant growth and light experiment, one plant is placed near the window and one inside the room. What is the independent variable?",
    options: [
      { key: "A", text: "Amount of light / plant location" },
      { key: "B", text: "Plant height" },
      { key: "C", text: "Amount of water" },
      { key: "D", text: "Amount of fertilizer" },
    ],
    answer: "A",
    hint: "Location changes how much light each plant receives — that is what is deliberately varied.",
  },
  {
    id: "12-4",
    section: "1.2",
    difficulty: "Foundation",
    stem: "In the same plant experiment, the student records plant heights each week. What is the dependent variable?",
    options: [
      { key: "A", text: "Amount of fertilizer" },
      { key: "B", text: "Type of pot" },
      { key: "C", text: "Amount of light / plant location" },
      { key: "D", text: "Plant height" },
    ],
    answer: "D",
    hint: "Height is the measured outcome that may change because of light.",
  },
  {
    id: "12-5",
    section: "1.2",
    difficulty: "Standard",
    stem: "In the plant growth and light experiment, which of the following is a controlled variable?",
    options: [
      { key: "A", text: "Amount of light / plant location" },
      { key: "B", text: "Amount of water given to each plant" },
      { key: "C", text: "Plant height after one week" },
      { key: "D", text: "How fast the plant grows" },
    ],
    answer: "B",
    hint: "Controlled variables are kept the same so the test is fair (e.g. same water and fertilizer).",
  },
];
